singleheader.py fixes for Windows and newer Python
Windows assumes cp1252 resulting in:
	  ...
	  File "c:\src\dyibicc\scratch\STC\src\singleheader.py", line 47, in process_file
	    process_file(
	  File "c:\src\dyibicc\scratch\STC\src\singleheader.py", line 28, in process_file
	    for line in f:
	  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 23, in decode
	    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
		   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 426: character maps to <undefined>

Additionally, \* seems to have changed in recent Py3 versions (?), so
they need an extra backslash:

	...\STC\src\singleheader.py:30: SyntaxWarning: invalid escape sequence '\*'
	  if re.search('/\*.*?\*/', line):